"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { copy, type Locale } from "./copy";
import { DriverControlScene, DriverBenefitsGrid, RiderJourneyScene, SafetySequence } from "./product-scenes";
import { SiteFooter } from "./site-footer";

const languages: Locale[]=["nl","en","ar"];
const text={
nl:{why:"Waarom HeyCaby",eyebrow:"Gebouwd door chauffeurs. Voor iedereen.",heroA:"Een taxi-app die",heroB:"eerlijk rijdt.",heroBody:"Chauffeurs houden 100% van iedere ritprijs. Rijders zien hun hele reis live, van de eerste zoekopdracht tot veilig thuis.",book:"Boek met vertrouwen",driver:"Ik ben chauffeur",commission:"ritcommissie",forDriver:"voor de chauffeur",visible:"zichtbaar veilig",promise:"DE HEYCABY BELOFTE",promiseTitle:"Als de chauffeur eerlijk verdient, kan iedereen beter rijden.",promises:["Geen algoritme dat de ritprijs afroomt.","Geen verborgen verhaal achter je rit.","Eén lokale community die elkaar kent."],rider:"VOOR RIJDERS",riderTitle:"Je rit vertelt altijd waar je aan toe bent.",riderBody:"Geen vage veiligheidsbelofte. HeyCaby maakt elke stap zichtbaar en begrijpelijk.",chapter:"01 — LIVE REIS",liveTitle:"Je hoeft de app niet open te houden om bij te blijven.",liveBody:"Van chauffeur gevonden tot aankomst: je ziet de identiteit, auto, ETA en ritstatus op het juiste moment. Deel de reis met mensen die belangrijk voor je zijn.",livePoints:["Geverifieerde chauffeur en voertuig","Live positie en aankomsttijd","Rit delen en veiligheidsacties"],forDrivers:"VOOR CHAUFFEURS",driverTitle:["Jouw taxi.","Jouw manier.","Jouw geld."],driverBody:"HeyCaby is gebouwd door chauffeurs die klaar waren met commissie op hun eigen werk. Jij bepaalt je tarief en houdt de volledige ritprijs.",perRide:"commissie op iedere rit",benefits:[["Zet jezelf online","Werk wanneer jij wilt. Je status blijft actief terwijl jij onderweg bent."],["Bepaal jouw tarief","Jouw onderneming, jouw kilometers, jouw prijs."],["Verdien op de terugweg","Taxi Terug vult lege kilometers met een rit op jouw route."]],built:"GEBOUWD IN NEDERLAND",communityTitle:["Geen taxiplatform boven de community.","Een platform van de community."],communityBody:"De functies komen uit het echte werk: tariefcontrole, favoriete chauffeurs, Taxi Terug en een transparant verdienmodel. Niet bedacht vanuit een boardroom, maar vanuit de bestuurdersstoel.",communityImageAlt:"Nederlandse taxichauffeurs bij elkaar in Rotterdam — een community-platform gebouwd vanuit de bestuurdersstoel.",communityCaption:"Rotterdam → Nederland",ready:"KLAAR OM TE RIJDEN?",choose:"Kies jouw kant van de rit.",riderCard:"Ik wil een rit",riderCardBody:"Boek lokaal. Volg live. Kom vertrouwd aan.",driverCard:"Ik ben chauffeur",driverCardBody:"Pak de tools. Houd de regie én je ritprijs.",footer:"Nederlands taxiplatform · Gebouwd door chauffeurs",iphone:"Download voor iPhone",android:"Download voor Android",skip:"Ga naar inhoud"},
en:{why:"Why HeyCaby",eyebrow:"Built by drivers. For everyone.",heroA:"A taxi app that",heroB:"drives fair.",heroBody:"Drivers keep 100% of every fare. Riders see their entire journey live, from the first search to arriving safely.",book:"Ride with confidence",driver:"I am a driver",commission:"ride commission",forDriver:"for the driver",visible:"visible safety",promise:"THE HEYCABY PROMISE",promiseTitle:"When the driver earns fairly, everyone rides better.",promises:["No algorithm taking a cut from every fare.","No hidden story behind your journey.","One local community that knows each other."],rider:"FOR RIDERS",riderTitle:"Your ride always tells you what happens next.",riderBody:"No vague safety promise. HeyCaby makes every step visible and understandable.",chapter:"01 — LIVE JOURNEY",liveTitle:"Stay informed without keeping the app open.",liveBody:"From driver found to arrival: see identity, vehicle, ETA and ride status at the right moment. Share the journey with the people who matter.",livePoints:["Verified driver and vehicle","Live position and arrival time","Ride sharing and safety actions"],forDrivers:"FOR DRIVERS",driverTitle:["Your taxi.","Your way.","Your money."],driverBody:"HeyCaby was built by drivers who were done paying commission on their own work. You set your rate and keep the entire fare.",perRide:"commission on every ride",benefits:[["Go online your way","Work when you want. Your status stays active while you are on the move."],["Set your own rate","Your business, your kilometres, your price."],["Earn on the way home","Taxi Terug fills empty kilometres with a ride on your route."]],built:"BUILT IN THE NETHERLANDS",communityTitle:["Not a taxi platform above the community.","A platform of the community."],communityBody:"The features come from real work: rate control, favourite drivers, Taxi Terug and a transparent earnings model. Designed from the driver’s seat, not a boardroom.",communityImageAlt:"Dutch taxi drivers together in Rotterdam — a community-built platform designed from the driver’s seat.",communityCaption:"Rotterdam → Netherlands",ready:"READY TO RIDE?",choose:"Choose your side of the ride.",riderCard:"I need a ride",riderCardBody:"Book local. Follow live. Arrive with confidence.",driverCard:"I am a driver",driverCardBody:"Take the tools. Keep control and your fare.",footer:"Dutch taxi platform · Built by drivers",iphone:"Download for iPhone",android:"Download for Android",skip:"Skip to content"},
ar:{why:"لماذا HeyCaby",eyebrow:"بناه السائقون. للجميع.",heroA:"تطبيق تاكسي",heroB:"يقود بعدل.",heroBody:"يحتفظ السائقون بكامل أجرة كل رحلة. ويرى الركاب رحلتهم مباشرة من البحث الأول حتى الوصول بأمان.",book:"احجز بثقة",driver:"أنا سائق",commission:"عمولة الرحلة",forDriver:"للسائق",visible:"أمان واضح",promise:"وعد HEYCABY",promiseTitle:"حين يكسب السائق بعدل، يسافر الجميع بشكل أفضل.",promises:["لا خوارزمية تقتطع من كل أجرة.","لا تفاصيل مخفية خلف رحلتك.","مجتمع محلي يعرف بعضه بعضًا."],rider:"للركاب",riderTitle:"رحلتك تخبرك دائمًا بما سيحدث.",riderBody:"لا وعود غامضة بالأمان. يجعل HeyCaby كل خطوة واضحة ومفهومة.",chapter:"٠١ — رحلة مباشرة",liveTitle:"ابقَ على اطلاع دون إبقاء التطبيق مفتوحًا.",liveBody:"من العثور على السائق حتى الوصول: شاهد الهوية والسيارة ووقت الوصول وحالة الرحلة في الوقت المناسب، وشاركها مع من يهمك.",livePoints:["سائق وسيارة موثّقان","موقع ووقت وصول مباشران","مشاركة الرحلة وإجراءات الأمان"],forDrivers:"للسائقين",driverTitle:["سيارتك.","طريقتك.","مالك."],driverBody:"بُني HeyCaby على يد سائقين سئموا دفع عمولة على عملهم. أنت تحدد سعرك وتحتفظ بكامل الأجرة.",perRide:"عمولة على كل رحلة",benefits:[["اتصل بطريقتك","اعمل عندما تريد وتبقى حالتك نشطة أثناء تنقلك."],["حدد سعرك","عملك وكيلومتراتك وسعرك."],["اكسب في طريق العودة","يملأ تاكسي العودة الكيلومترات الفارغة برحلة على مسارك."]],built:"صُنع في هولندا",communityTitle:["ليست منصة فوق المجتمع.","بل منصة من المجتمع."],communityBody:"تأتي المزايا من العمل الحقيقي: التحكم بالسعر والسائقون المفضلون وتاكسي العودة ونموذج أرباح واضح. صُممت من مقعد السائق لا من قاعة الاجتماعات.",communityImageAlt:"سائقو تاكسي هولنديون معًا في روتردام — منصة مجتمعية بُنيت من مقعد السائق.",communityCaption:"روتردام → هولندا",ready:"مستعد للانطلاق؟",choose:"اختر جانبك من الرحلة.",riderCard:"أريد رحلة",riderCardBody:"احجز محليًا. تابع مباشرة. صِل بثقة.",driverCard:"أنا سائق",driverCardBody:"خذ الأدوات واحتفظ بالتحكم والأجرة.",footer:"منصة تاكسي هولندية · بناها السائقون",iphone:"تنزيل للآيفون",android:"تنزيل لأندرويد",skip:"انتقل إلى المحتوى"}}
;

const deviceLocale=():Locale=>{if(typeof window==="undefined")return"nl";const saved=localStorage.getItem("heycaby-locale") as Locale|null;if(saved&&languages.includes(saved))return saved;const code=(navigator.languages?.[0]||navigator.language||"nl").split("-")[0].toLowerCase();return code==="ar"?"ar":code==="en"?"en":"nl"};
function StoreButtons({audience="rider",locale}:{audience?:"rider"|"driver";locale:Locale}){const driver=audience==="driver",s=text[locale];const ios=driver?"https://apps.apple.com/app/id6761512563":"https://apps.apple.com/app/id6761512910";const play=`https://play.google.com/store/apps/details?id=nl.heycaby.${audience}.app`;return <div className="store-row"><a href={ios} target="_blank" rel="noreferrer"><span>●</span><div><small>{s.iphone}</small><b>{driver?"HeyCaby Driver":"HeyCaby Rider"}</b></div></a><a href={play} target="_blank" rel="noreferrer"><span>▶</span><div><small>{s.android}</small><b>{driver?"HeyCaby Driver":"HeyCaby Rider"}</b></div></a></div>}
function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`reveal ${className}`}>{children}</div>}

export function MarketingExperience(){const[locale,setLocale]=useState<Locale>("nl");useEffect(()=>setLocale(deviceLocale()),[]);useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr";localStorage.setItem("heycaby-locale",locale)},[locale]);useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("visible",entry.isIntersecting)),{threshold:.1});document.querySelectorAll(".reveal").forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);const t=copy[locale],s=text[locale];return <>
<a className="skip-link" href="#main">{s.skip}</a><header className="site-header"><a className="brand" href="#top"><span>Hey</span><b>Caby</b></a><nav><a href="#ritten">{t.navRider}</a><a href="#chauffeurs">{t.navDriver}</a><a href="#waarom">{s.why}</a></nav><div className="header-actions"><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="nl">NL</option><option value="en">EN</option><option value="ar">AR</option></select><a className="primary-pill" href="#download">{t.download}</a></div></header>
<main id="main"><section className="hero section-shell" id="top"><Reveal className="hero-copy"><p className="eyebrow"><i/>{s.eyebrow}</p><h1>{s.heroA} <em>{s.heroB}</em></h1><p className="hero-body">{s.heroBody}</p><div className="hero-actions"><a className="primary-cta" href="#ritten">{s.book}<span>→</span></a><a className="text-cta" href="#chauffeurs">{s.driver}</a></div><div className="trust-strip"><span><b>0%</b>{s.commission}</span><span><b>100%</b>{s.forDriver}</span><span><b>A–Z</b>{s.visible}</span></div></Reveal><Reveal className="hero-stage"><RiderJourneyScene locale={locale}/></Reveal></section>
<section className="manifesto" id="waarom"><div className="section-shell"><p>{s.promise}</p><h2>{s.promiseTitle}</h2><div className="manifesto-grid">{s.promises.map(item=><span key={item}>{item}</span>)}</div></div></section>
<section className="rider-section section-shell" id="ritten"><Reveal className="section-title"><p className="kicker">{s.rider}</p><h2>{s.riderTitle}</h2><p>{s.riderBody}</p></Reveal><SafetySequence locale={locale}/><div className="story-panel"><RiderJourneyScene compact locale={locale}/><Reveal className="story-copy"><span className="chapter">{s.chapter}</span><h2>{s.liveTitle}</h2><p>{s.liveBody}</p><ul>{s.livePoints.map(item=><li key={item}>{item}</li>)}</ul></Reveal></div></section>
<section className="driver-section" id="chauffeurs"><div className="section-shell driver-grid"><Reveal className="driver-copy"><p className="kicker">{s.forDrivers}</p><h2>{s.driverTitle[0]}<br/>{s.driverTitle[1]}<br/><em>{s.driverTitle[2]}</em></h2><p>{s.driverBody}</p><div className="driver-proof"><strong>€0</strong><span>{s.perRide}</span></div><StoreButtons audience="driver" locale={locale}/></Reveal><Reveal><DriverControlScene locale={locale}/></Reveal></div><div className="section-shell"><DriverBenefitsGrid benefits={s.benefits as [string, string][]} locale={locale}/></div></section>
<section className="community-section section-shell"><Reveal><p className="kicker">{s.built}</p><h2>{s.communityTitle[0]}<br/><em>{s.communityTitle[1]}</em></h2><p>{s.communityBody}</p></Reveal><Reveal className="community-visual"><figure className="community-visual__frame"><Image className="community-visual__image" src="/community-platform-hero.png" alt={s.communityImageAlt} width={520} height={650} sizes="(max-width: 920px) min(88vw, 420px), 420px" /><figcaption className="community-visual__caption">{s.communityCaption}</figcaption></figure></Reveal></section>
<section className="download-section" id="download"><div className="section-shell download-inner"><div><p className="kicker">{s.ready}</p><h2>{s.choose}</h2></div><div className="download-cards"><article><span>R</span><h3>{s.riderCard}</h3><p>{s.riderCardBody}</p><StoreButtons locale={locale}/></article><article><span>C</span><h3>{s.driverCard}</h3><p>{s.driverCardBody}</p><StoreButtons audience="driver" locale={locale}/></article></div></div></section></main>
<SiteFooter locale={locale}/></>}
