-- Staging compatibility marker.
--
-- The blueprint waiting-time contract is stored in this repository under the
-- production migration timestamp 20260705054200. Staging already recorded this
-- later timestamp during alignment, so this file intentionally performs no DDL.
